/**
 * Tauri Command Contracts
 * Feature: Reading Session Manager with Audio Cache & Progress Persistence
 *
 * This file defines the TypeScript interfaces for all new Tauri commands.
 * These will be auto-generated by tauri-specta but are documented here for reference.
 */

// =============================================================================
// READING SESSION COMMANDS
// =============================================================================

/**
 * Create a new reading session
 * @command session_create
 */
export interface SessionCreateRequest {
  name: string;
  documentIds: string[];
}

export interface SessionCreateResponse {
  id: string;
  name: string;
  documents: SessionDocumentInfo[];
  createdAt: string;
  updatedAt: string;
  lastAccessedAt: string;
}

export interface SessionDocumentInfo {
  documentId: string;
  position: number;
  currentPage: number;
  scrollPosition: number;
  createdAt: string;
  // Denormalized document info for display
  title?: string;
  pageCount?: number;
}

/**
 * List all reading sessions
 * @command session_list
 */
export interface SessionListResponse {
  sessions: SessionSummary[];
}

export interface SessionSummary {
  id: string;
  name: string;
  documentCount: number;
  lastAccessedAt: string;
  createdAt: string;
}

/**
 * Get a single reading session with full details
 * @command session_get
 */
export interface SessionGetRequest {
  sessionId: string;
}

export type SessionGetResponse = SessionCreateResponse;

/**
 * Update a reading session
 * @command session_update
 */
export interface SessionUpdateRequest {
  sessionId: string;
  name?: string;
  documentIds?: string[];
}

export type SessionUpdateResponse = SessionCreateResponse;

/**
 * Delete a reading session
 * @command session_delete
 */
export interface SessionDeleteRequest {
  sessionId: string;
}

export interface SessionDeleteResponse {
  success: boolean;
}

/**
 * Restore a reading session (open all documents at saved positions)
 * @command session_restore
 */
export interface SessionRestoreRequest {
  sessionId: string;
}

export interface SessionRestoreResponse {
  success: boolean;
  session: SessionCreateResponse;
  missingDocuments: string[]; // Document IDs that couldn't be found
}

/**
 * Add document to existing session
 * @command session_add_document
 */
export interface SessionAddDocumentRequest {
  sessionId: string;
  documentId: string;
  position?: number; // If not provided, appends to end
}

export type SessionAddDocumentResponse = SessionCreateResponse;

/**
 * Remove document from session
 * @command session_remove_document
 */
export interface SessionRemoveDocumentRequest {
  sessionId: string;
  documentId: string;
}

export type SessionRemoveDocumentResponse = SessionCreateResponse;

/**
 * Update document position in session
 * @command session_update_document
 */
export interface SessionUpdateDocumentRequest {
  sessionId: string;
  documentId: string;
  currentPage?: number;
  scrollPosition?: number;
}

export type SessionUpdateDocumentResponse = SessionCreateResponse;

// =============================================================================
// AUDIO CACHE COMMANDS
// =============================================================================

/**
 * Get cache coverage statistics for a document
 * @command audio_cache_get_coverage
 */
export interface AudioCacheGetCoverageRequest {
  documentId: string;
  includePageStats?: boolean; // Default: false
}

export interface AudioCacheGetCoverageResponse {
  documentId: string;
  totalChunks: number;
  cachedChunks: number;
  coveragePercent: number;
  totalDurationMs: number;
  cachedSizeBytes: number;
  lastUpdated: string;
  pageStats?: PageCoverageStats[];
}

export interface PageCoverageStats {
  pageNumber: number;
  totalChunks: number;
  cachedChunks: number;
  coveragePercent: number;
  durationMs: number;
}

/**
 * Pre-buffer audio for a specific page
 * @command audio_cache_prebuffer_page
 */
export interface AudioCachePrebufferPageRequest {
  documentId: string;
  pageNumber: number;
  text: string;
  voiceId?: string;
}

export interface AudioCachePrebufferPageResponse {
  success: boolean;
  chunksBuffered: number;
  totalChunks: number;
  alreadyCached: number;
  durationMs: number;
}

/**
 * Clear cache for a specific document
 * @command audio_cache_clear_document
 */
export interface AudioCacheClearDocumentRequest {
  documentId: string;
}

export interface AudioCacheClearDocumentResponse {
  success: boolean;
  entriesCleared: number;
  bytesFreed: number;
}

/**
 * Get overall cache statistics
 * @command audio_cache_get_stats
 */
export interface AudioCacheGetStatsResponse {
  totalSizeBytes: number;
  entryCount: number;
  maxSizeBytes: number;
  oldestEntryAt?: string;
  newestEntryAt?: string;
  documentCount: number;
}

/**
 * Set cache size limit
 * @command audio_cache_set_limit
 */
export interface AudioCacheSetLimitRequest {
  maxSizeBytes: number;
}

export interface AudioCacheSetLimitResponse {
  success: boolean;
  previousLimit: number;
  newLimit: number;
  evictedCount: number; // Entries evicted to meet new limit
}

/**
 * Manually trigger LRU eviction
 * @command audio_cache_evict
 */
export interface AudioCacheEvictRequest {
  targetSizeBytes?: number; // Evict until under this size
  maxEntries?: number; // Evict at most this many entries
}

export interface AudioCacheEvictResponse {
  success: boolean;
  evictedCount: number;
  bytesFreed: number;
}

// =============================================================================
// AUDIO EXPORT COMMANDS
// =============================================================================

/**
 * Check if document is ready for export
 * @command audio_export_check_ready
 */
export interface AudioExportCheckReadyRequest {
  documentId: string;
  voiceId?: string;
}

export interface AudioExportCheckReadyResponse {
  ready: boolean;
  coveragePercent: number;
  missingChunks: MissingChunkInfo[];
  estimatedDurationMs: number;
  estimatedFileSizeBytes: number;
}

export interface MissingChunkInfo {
  pageNumber: number;
  chunkIndex: number;
  textPreview: string; // First 50 chars of missing chunk
}

/**
 * Export document audio to file
 * @command audio_export_document
 */
export interface AudioExportDocumentRequest {
  documentId: string;
  format: "mp3" | "m4b";
  outputPath: string;
  includeChapters: boolean;
  chapterStrategy: "page" | "document";
  voiceId?: string;
}

export interface AudioExportDocumentResponse {
  success: boolean;
  outputPath: string;
  format: string;
  totalDurationMs: number;
  chapterCount: number;
  fileSizeBytes: number;
  exportedAt: string;
}

/**
 * Cancel in-progress export
 * @command audio_export_cancel
 */
export interface AudioExportCancelResponse {
  success: boolean;
  wasRunning: boolean;
}

// =============================================================================
// EVENTS (Backend → Frontend)
// =============================================================================

/**
 * Event: Export progress update
 * @event audio-export:progress
 */
export interface AudioExportProgressEvent {
  phase:
    | "loading"
    | "concatenating"
    | "embedding"
    | "writing"
    | "complete"
    | "error";
  currentChunk: number;
  totalChunks: number;
  percent: number;
  estimatedRemainingMs: number;
  error?: string;
}

/**
 * Event: Cache coverage updated
 * @event audio-cache:coverage-updated
 */
export interface AudioCacheCoverageUpdatedEvent {
  documentId: string;
  coveragePercent: number;
  cachedChunks: number;
  totalChunks: number;
}

/**
 * Event: Cache eviction occurred
 * @event audio-cache:eviction
 */
export interface AudioCacheEvictionEvent {
  evictedCount: number;
  bytesFreed: number;
  reason: "size_limit" | "manual" | "document_deleted";
}

// =============================================================================
// ERROR CODES
// =============================================================================

export const ErrorCodes = {
  // Session errors
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_NAME_INVALID: "SESSION_NAME_INVALID",
  SESSION_DOCUMENT_LIMIT: "SESSION_DOCUMENT_LIMIT",

  // Cache errors
  CACHE_READ_ERROR: "CACHE_READ_ERROR",
  CACHE_WRITE_ERROR: "CACHE_WRITE_ERROR",
  CACHE_FULL: "CACHE_FULL",

  // Export errors
  EXPORT_NOT_READY: "EXPORT_NOT_READY",
  EXPORT_CANCELLED: "EXPORT_CANCELLED",
  EXPORT_WRITE_ERROR: "EXPORT_WRITE_ERROR",
  EXPORT_PATH_INVALID: "EXPORT_PATH_INVALID",

  // General errors
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DATABASE_ERROR: "DATABASE_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
