// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Add a new document to the library
 * Uses SHA-256 content hash as ID for duplicate detection
 */
async libraryAddDocument(filePath: string, title: string | null, pageCount: number | null) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_add_document", { filePath, title, pageCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a document by ID
 */
async libraryGetDocument(id: string) : Promise<Result<Document | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_get_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a document by file path
 */
async libraryGetDocumentByPath(filePath: string) : Promise<Result<Document | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_get_document_by_path", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update reading progress for a document
 */
async libraryUpdateProgress(id: string, currentPage: number, scrollPosition: number | null, lastTtsChunkId: string | null) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_progress", { id, currentPage, scrollPosition, lastTtsChunkId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update document metadata
 */
async libraryUpdateDocument(id: string, title: string | null, pageCount: number | null, fileHash: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_document", { id, title, pageCount, fileHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all documents in the library
 */
async libraryListDocuments(orderBy: string | null, limit: number | null, offset: number | null) : Promise<Result<Document[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_list_documents", { orderBy, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a document from the library
 */
async libraryRemoveDocument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_remove_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a document as opened
 */
async libraryOpenDocument(id: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_open_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a document's file still exists
 */
async libraryCheckFileExists(id: string) : Promise<Result<FileExistsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_check_file_exists", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update title of a document
 */
async libraryUpdateTitle(id: string, title: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_title", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Relocate a document to a new path
 */
async libraryRelocateDocument(id: string, newFilePath: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_relocate_document", { id, newFilePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new highlight
 */
async highlightsCreate(documentId: string, pageNumber: number, rects: Rect[], color: string, textContent: string | null) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_create", { documentId, pageNumber, rects, color, textContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create multiple highlights in a batch
 */
async highlightsBatchCreate(highlights: CreateHighlightInput[]) : Promise<Result<BatchCreateResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_batch_create", { highlights }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List highlights for a specific page
 */
async highlightsListForPage(documentId: string, pageNumber: number) : Promise<Result<ListHighlightsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_list_for_page", { documentId, pageNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all highlights for a document
 */
async highlightsListForDocument(documentId: string) : Promise<Result<ListHighlightsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_list_for_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single highlight by ID
 */
async highlightsGet(id: string) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a highlight's color or note
 */
async highlightsUpdate(id: string, color: string | null, note: string | null) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_update", { id, color, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a highlight
 */
async highlightsDelete(id: string) : Promise<Result<DeleteResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete all highlights for a document
 */
async highlightsDeleteForDocument(documentId: string) : Promise<Result<DeleteResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_delete_for_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export highlights to markdown or JSON
 */
async highlightsExport(documentId: string, format: string) : Promise<Result<ExportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_export", { documentId, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BatchCreateResponse = { highlights: Highlight[]; created: number }
/**
 * Input for creating a new highlight
 */
export type CreateHighlightInput = { documentId: string; pageNumber: number; rects: Rect[]; color: string; textContent: string | null }
export type DeleteResponse = { success: boolean; deleted: number | null }
/**
 * Represents a PDF document in the user's library
 */
export type Document = { id: string; filePath: string; title: string | null; pageCount: number | null; currentPage: number; scrollPosition: number; lastTtsChunkId: string | null; lastOpenedAt: string | null; fileHash: string | null; createdAt: string }
export type ExportResponse = { content: string; filename: string }
export type FileExistsResponse = { exists: boolean; filePath: string }
/**
 * Represents a text highlight within a document
 */
export type Highlight = { id: string; documentId: string; pageNumber: number; rects: Rect[]; color: string; textContent: string | null; note: string | null; createdAt: string; updatedAt: string | null }
/**
 * Response types for commands
 */
export type ListHighlightsResponse = { highlights: Highlight[] }
/**
 * Represents a rectangle for highlight positioning (page coordinates)
 */
export type Rect = { x: number; y: number; width: number; height: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
