// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Add a new document to the library
 * Uses SHA-256 content hash as ID for duplicate detection
 */
async libraryAddDocument(filePath: string, title: string | null, pageCount: number | null, expectedSha256: string | null) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_add_document", { filePath, title, pageCount, expectedSha256 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a document by ID
 */
async libraryGetDocument(id: string) : Promise<Result<Document | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_get_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a document by file path
 */
async libraryGetDocumentByPath(filePath: string) : Promise<Result<Document | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_get_document_by_path", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update reading progress for a document
 */
async libraryUpdateProgress(id: string, currentPage: number, scrollPosition: number | null, lastTtsChunkId: string | null) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_progress", { id, currentPage, scrollPosition, lastTtsChunkId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update document metadata
 */
async libraryUpdateDocument(id: string, title: string | null, pageCount: number | null, fileHash: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_document", { id, title, pageCount, fileHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all documents in the library
 */
async libraryListDocuments(orderBy: string | null, limit: number | null, offset: number | null) : Promise<Result<Document[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_list_documents", { orderBy, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a document from the library
 */
async libraryRemoveDocument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_remove_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a document as opened
 */
async libraryOpenDocument(id: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_open_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a document's file still exists
 */
async libraryCheckFileExists(id: string) : Promise<Result<FileExistsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_check_file_exists", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update title of a document
 */
async libraryUpdateTitle(id: string, title: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_update_title", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Relocate a document to a new path
 */
async libraryRelocateDocument(id: string, newFilePath: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_relocate_document", { id, newFilePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Relink a document whose file moved, without asking where it went.
 * 
 * The id already is the file's SHA-256, so a book that was renamed or filed
 * into a subfolder can be recovered by hashing what is nearby instead of being
 * shown as missing — reading position, highlights and shelves come back with
 * it. See `heal` for how "nearby" is bounded.
 * 
 * A document whose path still resolves is returned untouched, so the caller
 * can invoke this whenever a file fails to open without checking first.
 * 
 * The winning candidate is hashed twice — once to identify it, once inside
 * `library_relocate_document`. That is one extra read of one file, and it
 * keeps the content check that guards the UPDATE in a single place rather
 * than duplicated here.
 */
async libraryHealDocument(id: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_heal_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new highlight
 */
async highlightsCreate(documentId: string, pageNumber: number, rects: Rect[], color: string, textContent: string | null) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_create", { documentId, pageNumber, rects, color, textContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create multiple highlights in a batch
 */
async highlightsBatchCreate(highlights: CreateHighlightInput[]) : Promise<Result<BatchCreateResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_batch_create", { highlights }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List highlights for a specific page
 */
async highlightsListForPage(documentId: string, pageNumber: number) : Promise<Result<ListHighlightsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_list_for_page", { documentId, pageNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all highlights for a document
 */
async highlightsListForDocument(documentId: string) : Promise<Result<ListHighlightsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_list_for_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single highlight by ID
 */
async highlightsGet(id: string) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a highlight's color or note
 */
async highlightsUpdate(id: string, color: string | null, note: string | null) : Promise<Result<Highlight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_update", { id, color, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a highlight
 */
async highlightsDelete(id: string) : Promise<Result<DeleteResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete all highlights for a document
 */
async highlightsDeleteForDocument(documentId: string) : Promise<Result<DeleteResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_delete_for_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export highlights to markdown or JSON
 */
async highlightsExport(documentId: string, format: string) : Promise<Result<ExportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlights_export", { documentId, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a shelf.
 */
async collectionsCreate(name: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_create", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every shelf, ordered by name, each with its document count.
 */
async collectionsList() : Promise<Result<Collection[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a shelf.
 */
async collectionsRename(id: string, name: string) : Promise<Result<Collection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_rename", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a shelf. The documents filed on it stay in the library.
 */
async collectionsDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * File a document on a shelf.
 */
async collectionsAddDocument(collectionId: string, documentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_add_document", { collectionId, documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Take a document off a shelf.
 */
async collectionsRemoveDocument(collectionId: string, documentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_remove_document", { collectionId, documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every (document, shelf) pair, loaded in one call.
 */
async collectionsListMemberships() : Promise<Result<CollectionMembership[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collections_list_memberships") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One narrow cover-cache command. `store=None` reads; `Some(bytes)` writes.
 */
async coverCache(docId: string, store: number[] | null) : Promise<Result<number[] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cover_cache", { docId, store }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preflight the source file's size BEFORE the frontend reads a byte of it.
 * The cover pipeline skips oversized PDFs, and the skip must not cost a
 * whole-file read (Codex gate 121): the size is stat'd on the backend — no
 * fs-plugin permission surface; a custom command like the rest of the cover
 * API. Only library-registered paths can be stat'd (the WebView already
 * knows them; a stray path is rejected).
 */
async coverSourceSize(filePath: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cover_source_size", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new reading session
 */
async sessionCreate(name: string, documentIds: string[]) : Promise<Result<ReadingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_create", { name, documentIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a session by ID with all documents
 */
async sessionGet(sessionId: string) : Promise<Result<ReadingSession | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_get", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all sessions (summary only)
 */
async sessionList() : Promise<Result<SessionSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a session's name and/or documents
 */
async sessionUpdate(sessionId: string, name: string | null, documentIds: string[] | null) : Promise<Result<ReadingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_update", { sessionId, name, documentIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a session
 */
async sessionDelete(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_delete", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a session (touch last_accessed and check for missing documents)
 */
async sessionRestore(sessionId: string) : Promise<Result<SessionRestoreResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_restore", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a document to a session
 */
async sessionAddDocument(sessionId: string, documentId: string, position: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_add_document", { sessionId, documentId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a document from a session
 */
async sessionRemoveDocument(sessionId: string, documentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_remove_document", { sessionId, documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a document's reading position within a session
 */
async sessionUpdateDocument(sessionId: string, documentId: string, currentPage: number | null, scrollPosition: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_update_document", { sessionId, documentId, currentPage, scrollPosition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Touch a session to update its last_accessed_at timestamp
 */
async sessionTouch(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_touch", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the effective user configuration.
 */
async configGetEffective() : Promise<EffectiveConfig> {
    return await TAURI_INVOKE("config_get_effective");
},
/**
 * Initialize local TTS from validated native config. The WebView supplies no
 * URL and has no command that can mutate the destination.
 */
async aiTtsInitLocal() : Promise<Result<InitLocalResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_tts_init_local") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect Groq with a session-only API key. The production destination/model
 * are pinned inside the adapter and cannot be supplied by the WebView.
 */
async aiTtsInitGroq(apiKey: string) : Promise<Result<InitGroqResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_tts_init_groq", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the old route before selecting an already-connected provider.
 */
async aiTtsSwitchProvider(provider: TtsProvider) : Promise<Result<SwitchProviderResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_tts_switch_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiTts = { 
/**
 * Provider selection is native config only; the WebView receives read-only
 * effective state and has no command that can mutate the destination.
 */
provider?: AiTtsProvider; 
/**
 * Initial local-provider boundary is deliberately one exact loopback URL.
 * Broader addresses require a separate security decision.
 */
local_url?: string | null; 
/**
 * localStorage `ai-tts-storage.selectedVoiceId`.
 * 
 * NOT an `Option`, unlike `tts.voice`, and the round-trip property is why:
 * TOML has no null, so an absent key and a `None` are the same three bytes
 * of nothing. A field whose DEFAULT is `Some(rachel)` therefore cannot
 * express `None` in a file — writing `None` and reading it back yields
 * Rachel. `proptest` found exactly that asymmetry, and a type that cannot
 * represent the unrepresentable is the fix; the slice-2 writer would
 * otherwise silently "revert" a cleared voice.
 * 
 * (`tts.voice` keeps its `Option` legitimately: its default IS `None`, so
 * absent and `None` agree and the round-trip holds.)
 */
voice_id?: string; 
/**
 * localStorage `ai-tts-storage.speed` — clamped to 0.5..=4.5.
 */
speed?: number; 
/**
 * localStorage `ai-tts-storage.autoPageEnabled`
 */
auto_page?: boolean }
export type AiTtsProvider = "elevenlabs" | "local"
export type Appearance = { 
/**
 * SQLite `theme`
 */
theme?: Theme }
export type BatchCreateResponse = { highlights: Highlight[]; created: number }
export type Cache = { 
/**
 * SQLite `cache_settings.max_size_bytes`
 */
max_size_bytes?: number; 
/**
 * SQLite `cache_settings.eviction_policy`
 */
eviction_policy?: EvictionPolicy }
/**
 * A shelf — a named collection of documents.
 * 
 * `document_count` is denormalized for list display; it is computed by the
 * query, not stored.
 */
export type Collection = { id: string; name: string; documentCount: number; createdAt: string; updatedAt: string }
/**
 * One document filed under one shelf.
 * 
 * The whole membership table is small enough to load at once, which lets the
 * shelf filter and the per-document shelf picker work without further calls.
 */
export type CollectionMembership = { documentId: string; collectionId: string }
/**
 * The whole config file.
 * 
 * The ElevenLabs API key is deliberately absent: it is a secret, it is entered
 * at runtime today, and a config file is version-controlled (and world-readable
 * in a Nix store). Secrets do not belong here.
 */
export type Config = { schema_version?: number; appearance?: Appearance; highlight?: HighlightConfig; tts?: Tts; telemetry?: Telemetry; render?: Render; cache?: Cache; ai_tts?: AiTts }
/**
 * Input for creating a new highlight
 */
export type CreateHighlightInput = { documentId: string; pageNumber: number; rects: Rect[]; color: string; textContent: string | null }
export type DeleteResponse = { success: boolean; deleted: number | null }
/**
 * Represents a PDF document in the user's library
 */
export type Document = { id: string; filePath: string; title: string | null; pageCount: number | null; currentPage: number; scrollPosition: number; lastTtsChunkId: string | null; lastOpenedAt: string | null; fileHash: string | null; createdAt: string }
/**
 * The config Lectrice is actually running with, plus how it got there.
 * 
 * `warnings` and `error` are carried to the frontend so the UI can surface a
 * bad config to the user instead of leaving the finding in a log file nobody
 * reads. Slice 1 does not render them yet — the data is here so slice 2's UI
 * does not need a new command.
 */
export type EffectiveConfig = { 
/**
 * The effective settings (defaults when no file was loaded).
 */
config: Config; 
/**
 * Path consulted, if the platform had one.
 */
path: string | null; 
/**
 * True when a file was found AND successfully applied.
 */
loaded: boolean; 
/**
 * Non-fatal findings: unknown keys, clamped values, migration notes.
 */
warnings: string[]; 
/**
 * Set when a file existed but could not be used; `config` is the defaults.
 */
error: string | null }
export type EvictionPolicy = "lru"
export type ExportResponse = { content: string; filename: string }
export type FileExistsResponse = { exists: boolean; filePath: string }
/**
 * Represents a text highlight within a document
 */
export type Highlight = { id: string; documentId: string; pageNumber: number; rects: Rect[]; color: string; textContent: string | null; note: string | null; createdAt: string; updatedAt: string | null }
/**
 * Named `HighlightConfig`, not `Highlight`: specta flattens every exported
 * type into ONE TypeScript namespace, and `db::models::Highlight` (the
 * highlight entity) already owns that name. Two `export type Highlight`
 * declarations do not compile. The TOML section is still `[highlight]` —
 * that comes from the FIELD name, not the struct name.
 */
export type HighlightConfig = { 
/**
 * SQLite `highlight.defaultColor`
 */
default_color?: string; 
/**
 * SQLite `highlight.colors`
 */
colors?: string[] }
export type InitGroqResponse = { success: boolean; voicesCount: number; provider: TtsProvider; supportsWordTimings: boolean; maxTextUtf8Bytes: number }
export type InitLocalResponse = { success: boolean; voicesCount: number; provider: string; supportsWordTimings: boolean; maxTextUtf8Bytes: number; destination: string }
/**
 * Response types for commands
 */
export type ListHighlightsResponse = { highlights: Highlight[] }
export type QualityMode = "performance" | "balanced" | "ultra"
/**
 * A reading session containing multiple documents with saved positions
 */
export type ReadingSession = { id: string; name: string; documents: SessionDocument[]; createdAt: string; updatedAt: string; lastAccessedAt: string }
/**
 * Represents a rectangle for highlight positioning (page coordinates)
 */
export type Rect = { x: number; y: number; width: number; height: number }
export type Render = { 
/**
 * SQLite `render.qualityMode`
 */
quality_mode?: QualityMode; 
/**
 * SQLite `render.maxMegapixels` — clamped to 8..=48, the range the write
 * path already enforces.
 */
max_megapixels?: number; 
/**
 * SQLite `render.hwAccelerationEnabled`
 */
hw_acceleration?: boolean; 
/**
 * SQLite `render.debugOverlayEnabled`
 */
debug_overlay?: boolean }
/**
 * A document within a reading session with saved position
 */
export type SessionDocument = { documentId: string; position: number; currentPage: number; scrollPosition: number; createdAt: string; 
/**
 * Denormalized for display
 */
title: string | null; pageCount: number | null }
/**
 * Response for session restore operation
 */
export type SessionRestoreResponse = { success: boolean; session: ReadingSession; missingDocuments: string[] }
/**
 * Summary of a session for list operations
 */
export type SessionSummary = { id: string; name: string; documentCount: number; lastAccessedAt: string; createdAt: string }
export type SwitchProviderResponse = { success: boolean; provider: TtsProvider; voicesCount: number; supportsWordTimings: boolean; maxTextUtf8Bytes: number }
/**
 * Both fields default to `false`, which is exactly `#[derive(Default)]` — the
 * only section whose defaults are the type's own, so it is the only one that
 * does not need a hand-written impl.
 */
export type Telemetry = { 
/**
 * SQLite `telemetry.analytics`
 */
analytics?: boolean; 
/**
 * SQLite `telemetry.errors`
 */
errors?: boolean }
export type Theme = "light" | "dark" | "system"
export type Tts = { 
/**
 * SQLite `tts.rate` — clamped to 0.5..=3.0, as the settings store does.
 */
rate?: number; 
/**
 * SQLite `tts.voice` — `null` means "let the platform choose".
 */
voice?: string | null; 
/**
 * SQLite `tts.followAlong`
 */
follow_along?: boolean }
/**
 * Supported TTS providers
 */
export type TtsProvider = "elevenlabs" | "local" | "groq"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
