import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./tests/setup.ts"],
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "tests/**/*.{test,spec}.{ts,tsx}",
      // mockIPC headless E2E rung (jsdom, CI-runnable). The tauri-driver real
      // E2E lives in e2e/*.e2e.mjs and runs via wdio, never vitest.
      "e2e/**/*.spec.ts",
    ],
    exclude: ["node_modules", "dist", "src-tauri"],
    // Performance: Domain tests should complete quickly without external dependencies
    // Fail if any individual test takes longer than 5 seconds
    testTimeout: 5000,
    // Fail if the entire test suite takes too long (indicates test pollution)
    hookTimeout: 10000,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      exclude: [
        "node_modules",
        "dist",
        "src-tauri",
        "**/*.d.ts",
        "**/*.config.*",
        "**/tests/**",
        // E2E specs are test infrastructure, not source-under-test — don't let
        // their own functions drag the coverage denominator below the ratchet.
        "e2e/**",
        "src/main.tsx",
        // E2E-only bootstrap shim (VITE_E2E_NATIVE): drives the real play path for
        // the tauri-driver native-play E2E, never imported by vitest. Same class
        // as e2e/** — test infrastructure, excluded from the coverage denominator.
        "src/e2e-native-bootstrap.ts",
        "src/vite-env.d.ts",
        // Generated by `cargo run --example regenerate_bindings`, never edited
        // by hand, and already asserted byte-for-byte against what specta emits
        // (src-tauri/tests/bindings_contract.rs). Each generated function is a
        // try/catch around TAURI_INVOKE, so covering one measures the code
        // generator, not this repo. Leaving it in the denominator made the
        // ratchet fight the typed-surface migration: every command moved onto
        // the typed surface adds ~13 uncovered generated lines, and a command
        // the frontend does not call yet can never earn them back. 065 is where
        // that bit — +130 lines took the measured figure from 62.33% to 61.93%
        // against a 62% floor, with no test deleted and no behaviour changed.
        "src/lib/bindings.ts",
      ],
      // Coverage ratchet — last raised by 074-app-root-reachability
      // (02/08/2026).
      // Floors are pinned just under the MEASURED baseline at this commit, not
      // an aspirational 80%. They act as a REGRESSION gate — coverage may not
      // drop below the floor — and MUST be ratcheted UP as tests are added,
      // never silently down. Target: 80 across the board.
      // Policy + ratchet history: docs/coverage-budget.md.
      //
      // 097-coverage-ratchet (07/08/2026): CI run 31215577664 at `4ff16f3`
      // (default parallel pool — CI's real mode) measured 76.42 / 90.58 /
      // 72.84 / 76.42 for lines / branches / functions / statements. That is
      // 8.42 points of unratcheted headroom the previous triage called
      // "close" — it is not. Floors raised to lines 76 / statements 76 /
      // functions 72; branches stays 90 because pool mode shifts which
      // branches execute and 90.58 leaves no safe integer above it.
      // See docs/coverage-budget.md for the CI baseline and earlier
      // ratchets.
      thresholds: {
        lines: 76,
        functions: 72,
        branches: 90,
        statements: 76,
      },
    },
  },
});
