/**
 * Spoken-form unit corpus (en + pt-BR) — data only.
 *
 * Design of record: `corpus-design.md` in the audible-quality wave directory
 * (Fleet Task Evidence/lectrice-audible-2026-09-23), grounded in
 * `src/lib/speech-normalization.ts` and W4-terminology.md's class table.
 *
 * `shipped` expectations are proven by `speech-normalization.corpus.test.ts`;
 * every other status encodes a target for a future slice and is exercised as
 * deferred markers, so the suite stays green while the skeleton stays honest.
 */

export type CorpusLocale = "en" | "pt-BR";

export type CorpusStage = "normalization" | "extraction" | "lexicon";

export type CorpusStatus =
  | "shipped"
  | "design-of-record"
  | "policy-pending"
  | "other-stage";

export interface SpokenFormPair {
  /** Stable id, used as the test title. */
  id: string;
  /** W4-terminology.md class (A1, B1, D2, E2, …). */
  klass: string;
  stage: CorpusStage;
  locale: CorpusLocale;
  /** The written form. Single token unless the note says otherwise. */
  input: string;
  /** The desired spoken form; for refusals, `target === input`. */
  target: string;
  status: CorpusStatus;
  /** Open-conflict variant (e.g. B1: spec-234 vs mission wording). */
  alternativeTarget?: string;
  note?: string;
}

const REFUSALS: SpokenFormPair[] = [
  {
    id: "G-guard-01",
    klass: "B5",
    stage: "normalization",
    locale: "en",
    input: "2022-2023",
    target: "2022-2023",
    status: "shipped",
    note: "range: hyphen is a blocking neighbour",
  },
  {
    id: "G-guard-02",
    klass: "D5",
    stage: "normalization",
    locale: "pt-BR",
    input: "12/05",
    target: "12/05",
    status: "shipped",
    note: "date-shaped: slash is a blocking neighbour",
  },
  {
    id: "G-guard-03",
    klass: "A5",
    stage: "normalization",
    locale: "en",
    input: "A2022",
    target: "A2022",
    status: "shipped",
    note: "letter neighbour blocks",
  },
  {
    id: "G-guard-04",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "12345",
    target: "12345",
    status: "shipped",
    note: ">4 plain digits read as an identifier",
  },
  {
    id: "G-guard-05",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "007",
    target: "007",
    status: "shipped",
    note: "leading zeros refused",
  },
  {
    id: "G-guard-06",
    klass: "B2",
    stage: "normalization",
    locale: "en",
    input: "2.4.1",
    target: "2.4.1",
    status: "shipped",
    note: "malformed decimal refused whole, never decays to a prefix",
  },
  {
    id: "G-guard-07",
    klass: "currency",
    stage: "normalization",
    locale: "en",
    input: "$1.5",
    target: "$1.5",
    status: "shipped",
    note: "minor unit must be exactly two digits",
  },
];

export const SPOKEN_FORM_CORPUS: SpokenFormPair[] = [
  // --- integers (shipped) ---
  {
    id: "N-en-int-01",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "42",
    target: "forty-two",
    status: "shipped",
    note: "en tens-ones hyphenates",
  },
  {
    id: "N-en-int-02",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "2022",
    target: "two thousand twenty-two",
    status: "shipped",
    note: "no 'and' in en",
  },
  {
    id: "N-en-int-03",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "1,234",
    target: "one thousand two hundred thirty-four",
    status: "shipped",
  },
  {
    id: "N-en-int-04",
    klass: "integer",
    stage: "normalization",
    locale: "en",
    input: "7",
    target: "seven",
    status: "shipped",
  },
  {
    id: "N-pt-int-01",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "42",
    target: "quarenta e dois",
    status: "shipped",
  },
  {
    id: "N-pt-int-02",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "2022",
    target: "dois mil e vinte e dois",
    status: "shipped",
    note: "'e' join: last group < 100",
  },
  {
    id: "N-pt-int-03",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "1234",
    target: "mil duzentos e trinta e quatro",
    status: "shipped",
    note: "never 'um mil' (W4 §5.1 paraphrase differs — code wins)",
  },
  {
    id: "N-pt-int-04",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "1.234",
    target: "mil duzentos e trinta e quatro",
    status: "shipped",
    note: "pt grouping",
  },
  {
    id: "N-pt-int-05",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "100",
    target: "cem",
    status: "shipped",
  },
  {
    id: "N-pt-int-06",
    klass: "integer",
    stage: "normalization",
    locale: "pt-BR",
    input: "101",
    target: "cento e um",
    status: "shipped",
  },
  // --- decimals & percent (shipped; pt fraction reading policy-pending) ---
  {
    id: "N-en-dec-01",
    klass: "decimal",
    stage: "normalization",
    locale: "en",
    input: "3.14",
    target: "three point one four",
    status: "shipped",
  },
  {
    id: "N-en-dec-02",
    klass: "decimal",
    stage: "normalization",
    locale: "en",
    input: "1,234.56",
    target: "one thousand two hundred thirty-four point five six",
    status: "shipped",
  },
  {
    id: "N-pt-dec-01",
    klass: "decimal",
    stage: "normalization",
    locale: "pt-BR",
    input: "3,14",
    target: "três vírgula um quatro",
    status: "shipped",
    note: "current per-digit fraction; see N-pt-dec-01T for the W4 policy",
  },
  {
    id: "N-pt-dec-01T",
    klass: "decimal",
    stage: "normalization",
    locale: "pt-BR",
    input: "3,14",
    target: "três vírgula catorze",
    status: "policy-pending",
    note: "W4 §5.3.1 two-digit cardinal fraction; confirm vs W5 corpus + native review",
  },
  {
    id: "N-en-pct-01",
    klass: "percent",
    stage: "normalization",
    locale: "en",
    input: "90%",
    target: "ninety percent",
    status: "shipped",
  },
  {
    id: "N-en-pct-02",
    klass: "percent",
    stage: "normalization",
    locale: "en",
    input: "50 %",
    target: "fifty percent",
    status: "shipped",
    note: "space before % belongs to the token",
  },
  {
    id: "N-pt-pct-01",
    klass: "percent",
    stage: "normalization",
    locale: "pt-BR",
    input: "90%",
    target: "noventa por cento",
    status: "shipped",
  },
  // --- currency (shipped) ---
  {
    id: "N-en-cur-01",
    klass: "currency",
    stage: "normalization",
    locale: "en",
    input: "$1,234.56",
    target: "one thousand two hundred thirty-four dollars and fifty-six cents",
    status: "shipped",
  },
  {
    id: "N-en-cur-02",
    klass: "currency",
    stage: "normalization",
    locale: "en",
    input: "$5",
    target: "five dollars",
    status: "shipped",
  },
  {
    id: "N-en-cur-03",
    klass: "currency",
    stage: "normalization",
    locale: "en",
    input: "$1",
    target: "one dollar",
    status: "shipped",
  },
  {
    id: "N-en-cur-04",
    klass: "currency",
    stage: "normalization",
    locale: "en",
    input: "£2.50",
    target: "two pounds and fifty pence",
    status: "shipped",
    note: "minor-unit words follow the symbol",
  },
  {
    id: "N-pt-cur-01",
    klass: "currency",
    stage: "normalization",
    locale: "pt-BR",
    input: "R$ 1.234,56",
    target: "mil duzentos e trinta e quatro reais e cinquenta e seis centavos",
    status: "shipped",
    note: "flagship pair; differs from W4 §5.1's 'um mil…' paraphrase",
  },
  {
    id: "N-pt-cur-02",
    klass: "currency",
    stage: "normalization",
    locale: "pt-BR",
    input: "R$ 1,00",
    target: "um real",
    status: "shipped",
    note: "minor 00 → major unit only",
  },
  {
    id: "N-pt-cur-03",
    klass: "currency",
    stage: "normalization",
    locale: "pt-BR",
    input: "R$ 2,50",
    target: "dois reais e cinquenta centavos",
    status: "shipped",
  },
  // --- time (shipped) ---
  {
    id: "N-en-time-01",
    klass: "time",
    stage: "normalization",
    locale: "en",
    input: "14:30",
    target: "fourteen thirty",
    status: "shipped",
  },
  {
    id: "N-en-time-02",
    klass: "time",
    stage: "normalization",
    locale: "en",
    input: "9:05",
    target: "nine oh five",
    status: "shipped",
    note: "single-digit minute",
  },
  {
    id: "N-en-time-03",
    klass: "time",
    stage: "normalization",
    locale: "en",
    input: "12:00",
    target: "twelve o'clock",
    status: "shipped",
  },
  {
    id: "N-pt-time-01",
    klass: "time",
    stage: "normalization",
    locale: "pt-BR",
    input: "14:30",
    target: "quatorze horas e trinta minutos",
    status: "shipped",
  },
  {
    id: "N-pt-time-02",
    klass: "time",
    stage: "normalization",
    locale: "pt-BR",
    input: "2:00",
    target: "duas horas",
    status: "shipped",
    note: "feminine 'duas'",
  },
  // --- deliberate refusals (shipped; target = input unchanged) ---
  ...REFUSALS,
  // --- pending classes (todo skeleton) ---
  {
    id: "T-acr-01",
    klass: "A1",
    stage: "lexicon",
    locale: "en",
    input: "BI",
    target: "B I",
    status: "design-of-record",
    note: "flagship initialism; letters only via rule/glossary",
  },
  {
    id: "T-acr-02",
    klass: "A1",
    stage: "lexicon",
    locale: "pt-BR",
    input: "BI",
    target: "B I",
    status: "design-of-record",
  },
  {
    id: "T-acr-03",
    klass: "A6",
    stage: "lexicon",
    locale: "en",
    input: "APIs",
    target: "A P Is",
    status: "design-of-record",
  },
  {
    id: "T-acr-04",
    klass: "A3",
    stage: "lexicon",
    locale: "en",
    input: "SQL",
    target: "SQL",
    status: "design-of-record",
    note: "never guess — unchanged until the user decides",
  },
  {
    id: "T-ref-01",
    klass: "B1",
    stage: "normalization",
    locale: "en",
    input: "Figure 3-1",
    target: "figure three dash one",
    status: "design-of-record",
    alternativeTarget: "figure three one",
    note: "CONFLICT (W4 §10.1): mission says 'figure three one'; spec 234 is the single place this changes",
  },
  {
    id: "T-ref-01M",
    klass: "B1",
    stage: "normalization",
    locale: "en",
    input: "Figure 3-1",
    target: "figure three one",
    status: "policy-pending",
    note: "the mission variant, kept visible until the wave decides",
  },
  {
    id: "T-ref-02",
    klass: "B2",
    stage: "normalization",
    locale: "en",
    input: "Section 4.2.1",
    target: "section four point two point one",
    status: "design-of-record",
  },
  {
    id: "T-ref-03",
    klass: "B3",
    stage: "normalization",
    locale: "en",
    input: "v0.2.0",
    target: "version zero point two point zero",
    status: "design-of-record",
    note: "prefix-gated",
  },
  {
    id: "T-ref-04",
    klass: "B4",
    stage: "normalization",
    locale: "en",
    input: "PR #238",
    target: "P R two hundred thirty-eight",
    status: "design-of-record",
  },
  {
    id: "T-ref-05",
    klass: "B5",
    stage: "normalization",
    locale: "en",
    input: "pp. 12-18",
    target: "pages twelve to eighteen",
    status: "design-of-record",
    note: "opt-in range rule",
  },
  {
    id: "T-id-01",
    klass: "C1",
    stage: "normalization",
    locale: "en",
    input: "speech_normalization",
    target: "speech normalization",
    status: "design-of-record",
    note: "snake_case → words; never say 'underscore'",
  },
  {
    id: "T-id-02",
    klass: "C2",
    stage: "normalization",
    locale: "en",
    input: "PDFReader",
    target: "P D F reader",
    status: "design-of-record",
    note: "capital run obeys A1",
  },
  {
    id: "T-id-03",
    klass: "C3",
    stage: "normalization",
    locale: "en",
    input: "MAX_RETRY",
    target: "max retry",
    status: "design-of-record",
  },
  {
    id: "T-unit-01",
    klass: "D1",
    stage: "normalization",
    locale: "en",
    input: "12 kg",
    target: "twelve kilograms",
    status: "design-of-record",
    note: "closed unit table",
  },
  {
    id: "T-unit-02",
    klass: "D1",
    stage: "normalization",
    locale: "pt-BR",
    input: "3,5 GB",
    target: "três vírgula cinco gigabytes",
    status: "design-of-record",
  },
  {
    id: "T-unit-03",
    klass: "D1",
    stage: "normalization",
    locale: "en",
    input: "90 km/h",
    target: "ninety kilometers per hour",
    status: "design-of-record",
  },
  {
    id: "T-date-01",
    klass: "D5",
    stage: "normalization",
    locale: "pt-BR",
    input: "23/09/2026",
    target: "vinte e três de setembro de dois mil e vinte e seis",
    status: "design-of-record",
    note: "opt-in, locale-anchored; never guess ambiguous dates",
  },
  {
    id: "T-ord-01",
    klass: "D7",
    stage: "normalization",
    locale: "en",
    input: "1st",
    target: "first",
    status: "design-of-record",
  },
  {
    id: "T-ord-02",
    klass: "D7",
    stage: "normalization",
    locale: "pt-BR",
    input: "1º",
    target: "primeiro",
    status: "design-of-record",
  },
  {
    id: "T-rom-01",
    klass: "D8",
    stage: "normalization",
    locale: "en",
    input: "Section IV",
    target: "section four",
    status: "design-of-record",
    note: "label-gated roman numerals",
  },
  {
    id: "T-hyph-01",
    klass: "E2",
    stage: "extraction",
    locale: "pt-BR",
    input: "dese- jo",
    target: "desejo",
    status: "other-stage",
    note: "extraction join (src/lib/pdf-text.ts), slice 293 — not this grammar",
  },
  {
    id: "T-name-01",
    klass: "E1",
    stage: "lexicon",
    locale: "en",
    input: "nginx",
    target: "engine ex",
    status: "other-stage",
    note: "user glossary/phoneme; target is illustrative (user rule decides)",
  },
];

/** Pairs the current grammar must already satisfy. */
export const SHIPPED_PAIRS = SPOKEN_FORM_CORPUS.filter(
  (pair) => pair.status === "shipped" && pair.stage === "normalization",
);

/** Pairs encoding targets for future slices (asserted as deferred markers). */
export const PENDING_PAIRS = SPOKEN_FORM_CORPUS.filter(
  (pair) => pair.status !== "shipped",
);
