/**
 * Type Contract Tests
 *
 * These tests verify that the TypeScript types generated by tauri-specta
 * match the expected port interfaces. This ensures type safety across
 * the Rust/TypeScript boundary.
 *
 * The tests use compile-time type assertions to verify structural compatibility.
 */

import { describe, it, expect } from 'vitest';
import type {
  Document as BindingDocument,
  Highlight as BindingHighlight,
  Rect as BindingRect,
  CreateHighlightInput,
  BatchCreateResponse,
  DeleteResponse,
  ExportResponse,
  FileExistsResponse,
  ListHighlightsResponse,
} from '../../lib/bindings';
import type {
  Document as PortDocument,
  FileExistsResponse as PortFileExistsResponse,
} from '../../ports/document-repository.port';
import type {
  Highlight as PortHighlight,
  Rect as PortRect,
  HighlightCreate,
  BatchCreateResponse as PortBatchCreateResponse,
  DeleteResponse as PortDeleteResponse,
  ExportResponse as PortExportResponse,
} from '../../ports/highlight-repository.port';

// Type compatibility tests below verify at compile time and runtime that
// binding types from tauri-specta are assignable to port types

describe('Type Contract Tests', () => {
  describe('Document type contract', () => {
    it('binding Document should be assignable to port Document', () => {
      // This test verifies at compile time that the binding type is compatible
      const bindingDoc: BindingDocument = {
        id: 'test-id',
        filePath: '/path/to/file.pdf',
        title: 'Test Title',
        pageCount: 100,
        currentPage: 1,
        scrollPosition: 0.5,
        lastTtsChunkId: null,
        lastOpenedAt: '2026-01-13T00:00:00Z',
        fileHash: 'abc123',
        createdAt: '2026-01-13T00:00:00Z',
      };

      // If this assignment compiles, the types are compatible
      const portDoc: PortDocument = bindingDoc;

      // Runtime verification that all fields are present
      expect(portDoc.id).toBe('test-id');
      expect(portDoc.filePath).toBe('/path/to/file.pdf');
      expect(portDoc.title).toBe('Test Title');
      expect(portDoc.pageCount).toBe(100);
      expect(portDoc.currentPage).toBe(1);
      expect(portDoc.scrollPosition).toBe(0.5);
      expect(portDoc.lastTtsChunkId).toBeNull();
      expect(portDoc.lastOpenedAt).toBe('2026-01-13T00:00:00Z');
      expect(portDoc.fileHash).toBe('abc123');
      expect(portDoc.createdAt).toBe('2026-01-13T00:00:00Z');
    });

    it('Document should have all required fields', () => {
      // Verify required fields exist in the type
      const requiredFields: (keyof PortDocument)[] = [
        'id',
        'filePath',
        'title',
        'pageCount',
        'currentPage',
        'scrollPosition',
        'lastTtsChunkId',
        'lastOpenedAt',
        'fileHash',
        'createdAt',
      ];

      // Create a sample document
      const doc: BindingDocument = {
        id: '1',
        filePath: '/test.pdf',
        title: null,
        pageCount: null,
        currentPage: 1,
        scrollPosition: 0,
        lastTtsChunkId: null,
        lastOpenedAt: null,
        fileHash: null,
        createdAt: '2026-01-13T00:00:00Z',
      };

      // Verify all fields exist
      for (const field of requiredFields) {
        expect(field in doc).toBe(true);
      }
    });

    it('FileExistsResponse should be compatible between binding and port', () => {
      const bindingResponse: FileExistsResponse = {
        exists: true,
        filePath: '/path/to/file.pdf',
      };

      const portResponse: PortFileExistsResponse = bindingResponse;

      expect(portResponse.exists).toBe(true);
      expect(portResponse.filePath).toBe('/path/to/file.pdf');
    });
  });

  describe('Highlight type contract', () => {
    it('binding Highlight should be assignable to port Highlight', () => {
      const bindingHighlight: BindingHighlight = {
        id: 'highlight-1',
        documentId: 'doc-1',
        pageNumber: 1,
        rects: [{ x: 0, y: 0, width: 100, height: 20 }],
        color: '#FFEB3B',
        textContent: 'highlighted text',
        note: null,
        createdAt: '2026-01-13T00:00:00Z',
        updatedAt: null,
      };

      // If this assignment compiles, the types are compatible
      const portHighlight: PortHighlight = bindingHighlight;

      expect(portHighlight.id).toBe('highlight-1');
      expect(portHighlight.documentId).toBe('doc-1');
      expect(portHighlight.pageNumber).toBe(1);
      expect(portHighlight.rects).toHaveLength(1);
      expect(portHighlight.color).toBe('#FFEB3B');
      expect(portHighlight.textContent).toBe('highlighted text');
      expect(portHighlight.note).toBeNull();
    });

    it('Rect should be compatible between binding and port', () => {
      const bindingRect: BindingRect = {
        x: 10.5,
        y: 20.3,
        width: 100,
        height: 15,
      };

      const portRect: PortRect = bindingRect;

      expect(portRect.x).toBe(10.5);
      expect(portRect.y).toBe(20.3);
      expect(portRect.width).toBe(100);
      expect(portRect.height).toBe(15);
    });

    it('CreateHighlightInput should be compatible with HighlightCreate port type', () => {
      const createInput: CreateHighlightInput = {
        documentId: 'doc-1',
        pageNumber: 1,
        rects: [{ x: 0, y: 0, width: 100, height: 20 }],
        color: '#4CAF50',
        textContent: 'test text',
      };

      // The binding input has textContent as required (string | null)
      // The port has textContent as optional (string | undefined)
      // We need to map between them in the adapter
      const portInput: HighlightCreate = {
        documentId: createInput.documentId,
        pageNumber: createInput.pageNumber,
        rects: createInput.rects,
        color: createInput.color,
        textContent: createInput.textContent ?? undefined,
      };

      expect(portInput.documentId).toBe('doc-1');
      expect(portInput.textContent).toBe('test text');
    });

    it('BatchCreateResponse should be compatible', () => {
      const bindingResponse: BatchCreateResponse = {
        highlights: [
          {
            id: 'h1',
            documentId: 'd1',
            pageNumber: 1,
            rects: [],
            color: '#000',
            textContent: null,
            note: null,
            createdAt: '2026-01-13T00:00:00Z',
            updatedAt: null,
          },
        ],
        created: 1,
      };

      const portResponse: PortBatchCreateResponse = {
        highlights: bindingResponse.highlights,
        created: bindingResponse.created,
      };

      expect(portResponse.created).toBe(1);
      expect(portResponse.highlights).toHaveLength(1);
    });

    it('DeleteResponse should be compatible', () => {
      const bindingResponse: DeleteResponse = {
        success: true,
        deleted: 5,
      };

      const portResponse: PortDeleteResponse = bindingResponse;

      expect(portResponse.success).toBe(true);
      expect(portResponse.deleted).toBe(5);
    });

    it('ExportResponse should be compatible', () => {
      const bindingResponse: ExportResponse = {
        content: '# Highlights\n\n...',
        filename: 'highlights.md',
      };

      const portResponse: PortExportResponse = bindingResponse;

      expect(portResponse.content).toContain('Highlights');
      expect(portResponse.filename).toBe('highlights.md');
    });

    it('ListHighlightsResponse should contain Highlight array', () => {
      const response: ListHighlightsResponse = {
        highlights: [
          {
            id: 'h1',
            documentId: 'd1',
            pageNumber: 1,
            rects: [],
            color: '#000',
            textContent: null,
            note: null,
            createdAt: '2026-01-13T00:00:00Z',
            updatedAt: null,
          },
        ],
      };

      expect(Array.isArray(response.highlights)).toBe(true);
      expect(response.highlights[0].id).toBe('h1');
    });
  });

  describe('Type serialization contracts', () => {
    it('Document nullable fields should use null not undefined', () => {
      // Rust uses Option<T> which serializes to null, not undefined
      const doc: BindingDocument = {
        id: '1',
        filePath: '/test.pdf',
        title: null, // Option<String> -> null
        pageCount: null, // Option<i32> -> null
        currentPage: 1,
        scrollPosition: 0,
        lastTtsChunkId: null,
        lastOpenedAt: null,
        fileHash: null,
        createdAt: '2026-01-13T00:00:00Z',
      };

      // Verify null is used (not undefined)
      expect(doc.title).toBeNull();
      expect(doc.pageCount).toBeNull();
      expect(doc.lastTtsChunkId).toBeNull();
      expect(doc.lastOpenedAt).toBeNull();
      expect(doc.fileHash).toBeNull();
    });

    it('Highlight nullable fields should use null not undefined', () => {
      const highlight: BindingHighlight = {
        id: 'h1',
        documentId: 'd1',
        pageNumber: 1,
        rects: [],
        color: '#000',
        textContent: null, // Option<String> -> null
        note: null, // Option<String> -> null
        createdAt: '2026-01-13T00:00:00Z',
        updatedAt: null, // Option<String> -> null
      };

      expect(highlight.textContent).toBeNull();
      expect(highlight.note).toBeNull();
      expect(highlight.updatedAt).toBeNull();
    });

    it('camelCase serialization should be consistent', () => {
      // Both Rust (serde) and TypeScript use camelCase
      const doc: BindingDocument = {
        id: '1',
        filePath: '/test.pdf', // not file_path
        title: null,
        pageCount: null, // not page_count
        currentPage: 1, // not current_page
        scrollPosition: 0, // not scroll_position
        lastTtsChunkId: null, // not last_tts_chunk_id
        lastOpenedAt: null, // not last_opened_at
        fileHash: null, // not file_hash
        createdAt: '2026-01-13T00:00:00Z', // not created_at
      };

      // Verify camelCase field names (this would fail at compile time if wrong)
      expect('filePath' in doc).toBe(true);
      expect('pageCount' in doc).toBe(true);
      expect('currentPage' in doc).toBe(true);
      expect('scrollPosition' in doc).toBe(true);
      expect('lastTtsChunkId' in doc).toBe(true);
      expect('lastOpenedAt' in doc).toBe(true);
      expect('fileHash' in doc).toBe(true);
      expect('createdAt' in doc).toBe(true);
    });
  });
});
