//! The generated TypeScript bindings must match the Rust command surface — and
//! the generator must still run at all.
//!
//! `src/lib/bindings.ts` is generated by tauri-specta and checked in. Nothing
//! regenerated it between 2026-01-25 and this test: the export runs only under
//! `#[cfg(debug_assertions)]`, and only at app *runtime*, so it fires when a
//! developer launches `tauri dev` and then remembers to commit the result. CI
//! builds release, so it never fired there and nothing compared the file to the
//! Rust it claims to describe.
//!
//! By the time this test was written the file was missing eight commands — the
//! whole `collections_*` family (shipped 2026-07-31) and `library_heal_document`
//! (2026-08-01). The adapters in `src/adapters/tauri/` compile against that
//! file, so a *changed* signature would have type-checked against the stale
//! definition and failed at runtime instead.
//!
//! Writing the test surfaced a worse consequence of the same gap. Specta
//! defaults to `BigIntExportBehavior::Fail`, `Collection::document_count` is an
//! `i64`, and the export is `expect`ed on the startup path, so from the moment
//! shelves landed `cargo run` died before opening a window:
//!
//! ```text
//! thread 'main' panicked at src/lib.rs:320:10:
//! Failed to export TypeScript bindings: BigIntForbidden(
//!   src/db/models.rs:24:48 -> src/db/models.rs:24:48.documentCount -> i64)
//! ```
//!
//! Nothing in CI runs a debug binary, so the whole `tauri dev` loop was broken
//! for a day with every automated check green. These tests call the export
//! through the same `bindings_exporter()` that startup uses, which is what makes
//! that failure reachable from `cargo test` — a second copy of the config here
//! would have kept passing while the app kept panicking.
//!
//! The drift also explains `src/lib/api/*.ts`, a second hand-written IPC surface
//! with different error semantics: commands added after January were unreachable
//! through the bindings, so wrappers filled the gap. The duplication is a
//! symptom, not an independent design choice.

use std::fs;
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

use tauri_pdf_reader_lib::{bindings_exporter, specta_builder, write_bindings};

/// The checked-in artifact, baked in at compile time so cargo rebuilds this
/// test when it changes.
const CHECKED_IN: &str = include_str!("../../src/lib/bindings.ts");

/// Regenerate the bindings into cargo's per-test temp dir and return them.
///
/// Writes under `CARGO_TARGET_TMPDIR` rather than `/tmp`: it is per-target and
/// not world-readable, and cargo cleans it.
///
/// The filename is unique per call because cargo runs the tests in a binary on
/// parallel threads, and every test here regenerates — a shared path would have
/// them writing over each other's output and reading back a torn file.
fn regenerate() -> String {
    static SEQ: AtomicUsize = AtomicUsize::new(0);
    let out = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(format!(
        "bindings_{}.ts",
        SEQ.fetch_add(1, Ordering::Relaxed)
    ));
    write_bindings(&specta_builder(), bindings_exporter(), &out)
        .expect("specta failed to export bindings");
    fs::read_to_string(&out).expect("generated bindings unreadable")
}

/// Every `TAURI_INVOKE("...")` target in a bindings file, sorted.
fn invoked_commands(source: &str) -> Vec<String> {
    let mut found: Vec<String> = source
        .match_indices("TAURI_INVOKE(\"")
        .filter_map(|(at, m)| {
            let rest = &source[at + m.len()..];
            rest.find('"').map(|end| rest[..end].to_string())
        })
        .collect();
    found.sort();
    found.dedup();
    found
}

/// The property that actually failed in practice: a command exists in Rust and
/// the frontend cannot reach it through the generated bindings.
///
/// Asserted separately from the byte-for-byte check below because it is the
/// diagnosis. A whole-file mismatch says only "regenerate"; this names the
/// missing commands, which is what tells you whether the diff is an intended
/// addition or an accident.
#[test]
fn bindings_expose_every_command_the_rust_surface_collects() {
    let generated = regenerate();
    let expected = invoked_commands(&generated);
    let actual = invoked_commands(CHECKED_IN);

    assert!(
        !expected.is_empty(),
        "regenerated bindings contain no commands at all — the export produced \
         something this test cannot read, so its result would be vacuous"
    );

    let missing: Vec<&String> = expected.iter().filter(|c| !actual.contains(c)).collect();
    let extra: Vec<&String> = actual.iter().filter(|c| !expected.contains(c)).collect();

    assert!(
        missing.is_empty() && extra.is_empty(),
        "src/lib/bindings.ts is out of sync with the Rust command surface.\n\
         missing from bindings.ts (callable in Rust, unreachable from TS): {missing:?}\n\
         stale in bindings.ts (no longer collected in Rust): {extra:?}\n\
         Regenerate with: cargo run --example regenerate_bindings"
    );
}

/// The stronger form: the file matches byte for byte, so a *changed* signature
/// is caught too — not only an added or removed command.
///
/// This holds only because `src/lib/bindings.ts` is in `.prettierignore`. Left
/// formatter-owned, the pre-commit hook would rewrite the generated output and
/// this test would fail on formatting rather than on drift.
#[test]
fn checked_in_bindings_are_byte_for_byte_what_specta_generates() {
    let generated = regenerate();

    assert_eq!(
        generated, CHECKED_IN,
        "src/lib/bindings.ts differs from freshly generated output.\n\
         Regenerate with: cargo run --example regenerate_bindings"
    );
}

/// Specta's output must not depend on iteration order, or the byte-for-byte
/// test above would flake instead of gating.
///
/// Scope, stated honestly: two calls in ONE process cannot see nondeterminism
/// that is seeded per process (a `HashMap` ordering fixed at startup would look
/// stable here). What covers that is the byte-for-byte test itself — it compares
/// against a file generated on a different machine in a different process, so
/// every CI run is the cross-process check. This test's value is diagnostic: if
/// both fail, the generator is unstable; if only the other fails, it is drift.
#[test]
fn generation_is_deterministic() {
    assert_eq!(
        regenerate(),
        regenerate(),
        "specta produced different output for the same command surface, so the \
         byte-for-byte check above cannot be trusted"
    );
}

/// A render that fails must leave the destination file alone.
///
/// This is the whole reason `write_bindings` exists instead of a call to
/// `Builder::export`, which truncates before it can fail. The exporter here is
/// deliberately the *unconfigured* one: specta defaults `bigint` to `Fail` and
/// `Collection::document_count` is an `i64`, so this reproduces the exact
/// failure that emptied `src/lib/bindings.ts` — against the real command
/// surface, not a fixture built to fail.
#[test]
fn a_failed_render_leaves_the_destination_untouched() {
    let dest = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("bindings_preserve.ts");
    let last_good = "// the bindings that were already there\n";
    fs::write(&dest, last_good).expect("could not seed the destination");

    let err = write_bindings(
        &specta_builder(),
        specta_typescript::Typescript::default(),
        &dest,
    )
    .expect_err(
        "the unconfigured exporter rendered successfully. If no BigInt reaches \
         the command surface any more, this test no longer reproduces the \
         failure it was written for and needs another way to force one",
    );

    assert!(
        matches!(err, specta_typescript::ExportError::BigIntForbidden(_)),
        "expected the BigInt failure this guards against, got: {err}"
    );
    assert_eq!(
        fs::read_to_string(&dest).expect("destination unreadable"),
        last_good,
        "a failed render overwrote the destination — write_bindings must render \
         before it writes, or a broken command surface destroys the checked-in \
         bindings on every debug startup"
    );
}

/// A *write* that fails must leave the destination alone too.
///
/// Rendering first only closes half of it. `fs::write` truncates as well, so a
/// write that dies partway takes the file with it — and the failure that gets
/// past `open` is a full disk or a quota, which is exactly the condition under
/// which a developer is least able to tell one wiped file from the rest of the
/// mess. Staging plus `rename` is what makes the destination all-or-nothing.
///
/// A full disk is not reproducible in a test, so the write is failed by
/// occupying the staging path with a *directory*. Same code path: `fs::write`
/// returns `Err`, `rename` never runs, and the assertion below is about the
/// destination either way.
#[test]
fn a_failed_write_leaves_the_destination_untouched() {
    let dest = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("bindings_write_fail.ts");
    let last_good = "// the bindings that were already there\n";
    fs::write(&dest, last_good).expect("could not seed the destination");

    let mut staging = dest.as_os_str().to_owned();
    staging.push(".staging");
    let staging = PathBuf::from(staging);
    fs::create_dir_all(&staging).expect("could not occupy the staging path");

    let err = write_bindings(&specta_builder(), bindings_exporter(), &dest).expect_err(
        "the write succeeded with a directory sitting on its staging path, so \
         write_bindings is no longer staging — it is writing the destination \
         directly, and a failed write destroys it",
    );

    assert!(
        matches!(err, specta_typescript::ExportError::Io(_)),
        "expected the staging write to fail with an io error, got: {err}"
    );
    assert_eq!(
        fs::read_to_string(&dest).expect("destination unreadable"),
        last_good,
        "a failed write overwrote the destination — write_bindings must stage the \
         render and rename it into place, or a full disk empties the checked-in \
         bindings"
    );

    fs::remove_dir_all(&staging).ok();
}

/// The crate's own source, baked in so editing either command list rebuilds this
/// test.
///
/// `tauri::generate_handler!` expands to a dispatch closure and exposes no list
/// at runtime, so the set of commands the app actually registers is not
/// reachable from a test the way `specta_builder()` is. Reading it out of the
/// source that declares it is the only way to compare the two — worth the
/// source-parsing because the alternative is not comparing them at all.
///
/// The source shows every feature's commands at once rather than one build's:
/// `native-tts` is not in `default`, so the eleven `tts_*` entries are registered
/// only where that feature is asked for. Both lists are read out of the same text,
/// so they stay consistent with each other, and a union is the conservative side
/// for an exception list to err on. The reverse — a *typed* command hidden behind
/// a feature, exported to bindings.ts but unregistered in a default build — cannot
/// be written: `collect_commands!` matches bare idents, so an attribute inside it
/// is `error: no rules expected '#'`, not a silent narrowing.
const LIB_RS: &str = include_str!("../src/lib.rs");

/// Registered with tauri but deliberately outside the typed surface.
///
/// A command in this list works — it is live in the app — but has no generated
/// binding, so the frontend reaches it through a hand-written wrapper in
/// `src/lib/api/` that names the command and its arguments as string literals.
/// Nothing checks those wrappers against Rust. Rename an argument and it
/// compiles on both sides and fails at runtime. That is the same class of defect
/// the byte-for-byte test above exists to catch, still open for these.
///
/// Two different reasons sit in here, and the difference matters:
///
/// - A minority genuinely cannot be typed. Specta needs a `specta::Type` for
///   every argument and return, and `serde_json::Value` has no TypeScript
///   shape — `SettingResponse { key, value: serde_json::Value }` carries one, so
///   the whole `settings_*` family is stuck until those payloads get real types.
/// - Most are just unmigrated. `session_*`, `audio_cache_*`, `ai_tts_*` and the
///   rest return ordinary structs (`ReadingSession`, `CacheStatsResponse`) that
///   would type fine; they were added after January without anyone extending
///   `collect_commands!`, and the return types lack a `specta::Type` derive only
///   because nothing ever asked for one.
///
/// They are not split into two lists here because the boundary cannot be decided
/// by grep: `serde_json::Value` is reached transitively through struct fields,
/// and this crate has several distinct types sharing a name across
/// `commands/` and `tauri_api/`, so a mechanical classification mislabels
/// entries. Resolve it per family when migrating that family.
///
/// This list is a ratchet, not an allowlist to add to. Shrink it by moving a
/// command into `collect_commands!` and regenerating. It grows only when a new
/// command is registered without types, and the test below makes that a
/// deliberate edit here rather than something nobody notices.
const COMMANDS_OUTSIDE_THE_TYPED_SURFACE: &[&str] = &[
    "ai_tts_cache_clear",
    "ai_tts_cache_info",
    "ai_tts_cache_invalidate_voice",
    "ai_tts_get_config",
    "ai_tts_get_state",
    "ai_tts_init",
    "ai_tts_list_voices",
    "ai_tts_pause",
    "ai_tts_prebuffer",
    "ai_tts_resume",
    "ai_tts_set_speed",
    "ai_tts_set_voice",
    "ai_tts_speak",
    "ai_tts_speak_with_timestamps",
    "ai_tts_stop",
    "audio_cache_clear_document",
    "audio_cache_evict",
    "audio_cache_get_coverage",
    "audio_cache_get_limit",
    "audio_cache_get_stats",
    "audio_cache_notify_coverage",
    "audio_cache_set_limit",
    "audio_export_cancel",
    "audio_export_check_ready",
    "audio_export_document",
    "clear_debug_logs",
    "clear_safe_mode",
    "export_debug_logs",
    "get_debug_logs",
    "get_hw_accel_status",
    "get_render_settings",
    "settings_delete",
    "settings_delete_v2",
    "settings_get",
    "settings_get_all",
    "settings_get_all_v2",
    "settings_get_v2",
    "settings_set",
    "settings_set_batch",
    "settings_set_batch_v2",
    "settings_set_v2",
    "tts_check_capabilities",
    "tts_get_state",
    "tts_init",
    "tts_list_voices",
    "tts_pause",
    "tts_resume",
    "tts_set_rate",
    "tts_set_voice",
    "tts_speak",
    "tts_speak_long",
    "tts_stop",
    "update_render_settings",
];

/// The bracket-balanced text between `<macro_name>![` and its matching `]`.
fn macro_body<'a>(source: &'a str, macro_name: &str) -> &'a str {
    let opening = format!("{macro_name}![");
    let start = source
        .find(&opening)
        .unwrap_or_else(|| panic!("{macro_name}! is not invoked in src/lib.rs"))
        + opening.len();

    let mut depth = 1usize;
    for (offset, c) in source[start..].char_indices() {
        match c {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return &source[start..start + offset];
                }
            }
            _ => {}
        }
    }
    panic!("{macro_name}! has no closing bracket in src/lib.rs")
}

/// The bare command identifiers inside `<macro_name>![ … ]`, sorted.
///
/// Both lists are one identifier per line, with `//` comments and
/// `#[cfg(feature = …)]` attributes on lines of their own, so the parse is: take
/// the body, drop each line's comment tail, keep the last `::` segment.
///
/// Every other line has to resolve to a command — an unreadable one panics rather
/// than being passed over. A parser that quietly drops what it cannot read would
/// be worse here than no parser at all: write `#[cfg(feature = "native-tts")]
/// tts_init,` on a single line, or wrap a name in `/* … */`, and it would fall out
/// of *both* lists at once, leaving them in perfect agreement about a command
/// neither had seen. Refusing the line turns that into a failure naming it.
fn commands_in_macro(source: &str, macro_name: &str) -> Vec<String> {
    let mut found: Vec<String> = macro_body(source, macro_name)
        .lines()
        .filter_map(|line| {
            let code = line.split("//").next().unwrap_or_default().trim();
            let is_an_attribute_of_its_own = code.starts_with("#[") && code.ends_with(']');
            if code.is_empty() || is_an_attribute_of_its_own {
                return None;
            }

            let name = code
                .trim_end_matches(',')
                .rsplit("::")
                .next()
                .unwrap_or_default()
                .trim();
            let looks_like_a_command = !name.is_empty()
                && name
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
            assert!(
                looks_like_a_command,
                "{macro_name}! has a line this test cannot read as a command, an \
                 attribute or a comment: {line:?}\n\
                 Keep one command per line and attributes on their own line, or teach \
                 commands_in_macro the new shape. A line it cannot read is a command \
                 it stops watching."
            );
            Some(name.to_string())
        })
        .collect();
    found.sort();
    found.dedup();
    found
}

/// Everything specta types must actually be registered, or the bindings promise
/// the frontend a command the app will refuse to dispatch.
///
/// This direction fails loudly at runtime rather than quietly — `invoke` on an
/// unregistered command rejects — but it fails in the app, on the user's
/// machine, and only on the code path that calls it. Here it fails in CI.
#[test]
fn every_typed_command_is_registered_with_tauri() {
    let typed = commands_in_macro(LIB_RS, "collect_commands");
    let registered = commands_in_macro(LIB_RS, "generate_handler");

    assert!(
        !typed.is_empty() && !registered.is_empty(),
        "parsed {} typed and {} registered commands out of src/lib.rs — one of \
         the lists stopped matching what this test knows how to read, so its \
         result would be vacuous",
        typed.len(),
        registered.len()
    );

    let unregistered: Vec<&String> = typed.iter().filter(|c| !registered.contains(c)).collect();
    assert!(
        unregistered.is_empty(),
        "collect_commands! types commands that generate_handler! does not \
         register, so bindings.ts exports functions that cannot be invoked: \
         {unregistered:?}"
    );
}

/// A newly registered command is typed, or its absence is written down here.
///
/// The gap this pins is real and large: most of the app's IPC — sessions, the
/// audio cache, both TTS engines, settings — is registered without types and
/// reached through hand-written wrappers that nothing compares to Rust. The
/// byte-for-byte test above gates the surface specta *collects*; it says nothing
/// about a command that was never collected, which is how a surface this size
/// stayed invisible.
///
/// Closing it is a per-family migration (each return type needs a
/// `specta::Type`), not one change. Until then this at least makes the gap
/// countable and stops it growing by accident: add a command to
/// `generate_handler!` alone and this test names it.
#[test]
fn every_registered_command_is_typed_or_a_recorded_exception() {
    let typed = commands_in_macro(LIB_RS, "collect_commands");
    let registered = commands_in_macro(LIB_RS, "generate_handler");

    let untyped: Vec<String> = registered
        .iter()
        .filter(|c| !typed.contains(c))
        .cloned()
        .collect();

    let newly_untyped: Vec<&String> = untyped
        .iter()
        .filter(|c| !COMMANDS_OUTSIDE_THE_TYPED_SURFACE.contains(&c.as_str()))
        .collect();
    let now_typed: Vec<&&str> = COMMANDS_OUTSIDE_THE_TYPED_SURFACE
        .iter()
        .filter(|c| !untyped.iter().any(|u| u == *c))
        .collect();

    assert!(
        newly_untyped.is_empty(),
        "registered with tauri but not typed by specta, and not recorded as an \
         exception: {newly_untyped:?}\n\
         Add each to collect_commands! (its argument and return types need a \
         specta::Type derive) and run: cargo run --example regenerate_bindings\n\
         If it genuinely cannot be typed, add it to \
         COMMANDS_OUTSIDE_THE_TYPED_SURFACE with the reason."
    );
    assert!(
        now_typed.is_empty(),
        "listed in COMMANDS_OUTSIDE_THE_TYPED_SURFACE but no longer untyped — \
         either typed now or gone: {now_typed:?}\n\
         Delete these entries; a stale exception list hides the next real gap."
    );
}
