//! The generated TypeScript bindings must match the Rust command surface — and
//! the generator must still run at all.
//!
//! `src/lib/bindings.ts` is generated by tauri-specta and checked in. Nothing
//! regenerated it between 2026-01-25 and this test: the export runs only under
//! `#[cfg(debug_assertions)]`, and only at app *runtime*, so it fires when a
//! developer launches `tauri dev` and then remembers to commit the result. CI
//! builds release, so it never fired there and nothing compared the file to the
//! Rust it claims to describe.
//!
//! By the time this test was written the file was missing eight commands — the
//! whole `collections_*` family (shipped 2026-07-31) and `library_heal_document`
//! (2026-08-01). The adapters in `src/adapters/tauri/` compile against that
//! file, so a *changed* signature would have type-checked against the stale
//! definition and failed at runtime instead.
//!
//! Writing the test surfaced a worse consequence of the same gap. Specta
//! defaults to `BigIntExportBehavior::Fail`, `Collection::document_count` is an
//! `i64`, and the export is `expect`ed on the startup path, so from the moment
//! shelves landed `cargo run` died before opening a window:
//!
//! ```text
//! thread 'main' panicked at src/lib.rs:320:10:
//! Failed to export TypeScript bindings: BigIntForbidden(
//!   src/db/models.rs:24:48 -> src/db/models.rs:24:48.documentCount -> i64)
//! ```
//!
//! Nothing in CI runs a debug binary, so the whole `tauri dev` loop was broken
//! for a day with every automated check green. These tests call the export
//! through the same `bindings_exporter()` that startup uses, which is what makes
//! that failure reachable from `cargo test` — a second copy of the config here
//! would have kept passing while the app kept panicking.
//!
//! The drift also explains `src/lib/api/*.ts`, a second hand-written IPC surface
//! with different error semantics: commands added after January were unreachable
//! through the bindings, so wrappers filled the gap. The duplication is a
//! symptom, not an independent design choice.

use std::fs;
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

use tauri_pdf_reader_lib::{bindings_exporter, specta_builder, write_bindings};

/// The checked-in artifact, baked in at compile time so cargo rebuilds this
/// test when it changes.
const CHECKED_IN: &str = include_str!("../../src/lib/bindings.ts");

/// Regenerate the bindings into cargo's per-test temp dir and return them.
///
/// Writes under `CARGO_TARGET_TMPDIR` rather than `/tmp`: it is per-target and
/// not world-readable, and cargo cleans it.
///
/// The filename is unique per call because cargo runs the tests in a binary on
/// parallel threads, and every test here regenerates — a shared path would have
/// them writing over each other's output and reading back a torn file.
fn regenerate() -> String {
    static SEQ: AtomicUsize = AtomicUsize::new(0);
    let out = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(format!(
        "bindings_{}.ts",
        SEQ.fetch_add(1, Ordering::Relaxed)
    ));
    write_bindings(&specta_builder(), bindings_exporter(), &out)
        .expect("specta failed to export bindings");
    fs::read_to_string(&out).expect("generated bindings unreadable")
}

/// Every `TAURI_INVOKE("...")` target in a bindings file, sorted.
fn invoked_commands(source: &str) -> Vec<String> {
    let mut found: Vec<String> = source
        .match_indices("TAURI_INVOKE(\"")
        .filter_map(|(at, m)| {
            let rest = &source[at + m.len()..];
            rest.find('"').map(|end| rest[..end].to_string())
        })
        .collect();
    found.sort();
    found.dedup();
    found
}

/// The property that actually failed in practice: a command exists in Rust and
/// the frontend cannot reach it through the generated bindings.
///
/// Asserted separately from the byte-for-byte check below because it is the
/// diagnosis. A whole-file mismatch says only "regenerate"; this names the
/// missing commands, which is what tells you whether the diff is an intended
/// addition or an accident.
#[test]
fn bindings_expose_every_command_the_rust_surface_collects() {
    let generated = regenerate();
    let expected = invoked_commands(&generated);
    let actual = invoked_commands(CHECKED_IN);

    assert!(
        !expected.is_empty(),
        "regenerated bindings contain no commands at all — the export produced \
         something this test cannot read, so its result would be vacuous"
    );

    let missing: Vec<&String> = expected.iter().filter(|c| !actual.contains(c)).collect();
    let extra: Vec<&String> = actual.iter().filter(|c| !expected.contains(c)).collect();

    assert!(
        missing.is_empty() && extra.is_empty(),
        "src/lib/bindings.ts is out of sync with the Rust command surface.\n\
         missing from bindings.ts (callable in Rust, unreachable from TS): {missing:?}\n\
         stale in bindings.ts (no longer collected in Rust): {extra:?}\n\
         Regenerate with: cargo run --example regenerate_bindings"
    );
}

/// The stronger form: the file matches byte for byte, so a *changed* signature
/// is caught too — not only an added or removed command.
///
/// This holds only because `src/lib/bindings.ts` is in `.prettierignore`. Left
/// formatter-owned, the pre-commit hook would rewrite the generated output and
/// this test would fail on formatting rather than on drift.
#[test]
fn checked_in_bindings_are_byte_for_byte_what_specta_generates() {
    let generated = regenerate();

    assert_eq!(
        generated, CHECKED_IN,
        "src/lib/bindings.ts differs from freshly generated output.\n\
         Regenerate with: cargo run --example regenerate_bindings"
    );
}

/// Specta's output must not depend on iteration order, or the byte-for-byte
/// test above would flake instead of gating.
///
/// Scope, stated honestly: two calls in ONE process cannot see nondeterminism
/// that is seeded per process (a `HashMap` ordering fixed at startup would look
/// stable here). What covers that is the byte-for-byte test itself — it compares
/// against a file generated on a different machine in a different process, so
/// every CI run is the cross-process check. This test's value is diagnostic: if
/// both fail, the generator is unstable; if only the other fails, it is drift.
#[test]
fn generation_is_deterministic() {
    assert_eq!(
        regenerate(),
        regenerate(),
        "specta produced different output for the same command surface, so the \
         byte-for-byte check above cannot be trusted"
    );
}

/// A render that fails must leave the destination file alone.
///
/// This is the whole reason `write_bindings` exists instead of a call to
/// `Builder::export`, which truncates before it can fail. The exporter here is
/// deliberately the *unconfigured* one: specta defaults `bigint` to `Fail` and
/// `Collection::document_count` is an `i64`, so this reproduces the exact
/// failure that emptied `src/lib/bindings.ts` — against the real command
/// surface, not a fixture built to fail.
#[test]
fn a_failed_render_leaves_the_destination_untouched() {
    let dest = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("bindings_preserve.ts");
    let last_good = "// the bindings that were already there\n";
    fs::write(&dest, last_good).expect("could not seed the destination");

    let err = write_bindings(
        &specta_builder(),
        specta_typescript::Typescript::default(),
        &dest,
    )
    .expect_err(
        "the unconfigured exporter rendered successfully. If no BigInt reaches \
         the command surface any more, this test no longer reproduces the \
         failure it was written for and needs another way to force one",
    );

    assert!(
        matches!(err, specta_typescript::ExportError::BigIntForbidden(_)),
        "expected the BigInt failure this guards against, got: {err}"
    );
    assert_eq!(
        fs::read_to_string(&dest).expect("destination unreadable"),
        last_good,
        "a failed render overwrote the destination — write_bindings must render \
         before it writes, or a broken command surface destroys the checked-in \
         bindings on every debug startup"
    );
}

/// A *write* that fails must leave the destination alone too.
///
/// Rendering first only closes half of it. `fs::write` truncates as well, so a
/// write that dies partway takes the file with it — and the failure that gets
/// past `open` is a full disk or a quota, which is exactly the condition under
/// which a developer is least able to tell one wiped file from the rest of the
/// mess. Staging plus `rename` is what makes the destination all-or-nothing.
///
/// A full disk is not reproducible in a test, so the write is failed by
/// occupying the staging path with a *directory*. Same code path: `fs::write`
/// returns `Err`, `rename` never runs, and the assertion below is about the
/// destination either way.
#[test]
fn a_failed_write_leaves_the_destination_untouched() {
    let dest = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("bindings_write_fail.ts");
    let last_good = "// the bindings that were already there\n";
    fs::write(&dest, last_good).expect("could not seed the destination");

    let mut staging = dest.as_os_str().to_owned();
    staging.push(".staging");
    let staging = PathBuf::from(staging);
    fs::create_dir_all(&staging).expect("could not occupy the staging path");

    let err = write_bindings(&specta_builder(), bindings_exporter(), &dest).expect_err(
        "the write succeeded with a directory sitting on its staging path, so \
         write_bindings is no longer staging — it is writing the destination \
         directly, and a failed write destroys it",
    );

    assert!(
        matches!(err, specta_typescript::ExportError::Io(_)),
        "expected the staging write to fail with an io error, got: {err}"
    );
    assert_eq!(
        fs::read_to_string(&dest).expect("destination unreadable"),
        last_good,
        "a failed write overwrote the destination — write_bindings must stage the \
         render and rename it into place, or a full disk empties the checked-in \
         bindings"
    );

    fs::remove_dir_all(&staging).ok();
}
