#!/usr/bin/env bash
#
# Reproducible runner for the packaged open-journey E2E
# (e2e/open-journey.e2e.mjs) — two phases over ONE hermetic profile:
#
#   phase open-good    — VITE_E2E_OPEN_PATH = the GOOD fixture (Fixture B);
#                        the actor clicks Toolbar Open; the reader surface
#                        must display. Expected RED on main (the claimed
#                        defect: the document loads, the surface never
#                        changes).
#   phase open-corrupt — VITE_E2E_OPEN_PATH = a garbage .pdf generated by
#                        the observer; the open flow throws; an error must
#                        be visible on the shown surface. Expected RED on
#                        main (the failure is silent).
#
# The GTK file dialog is the WebDriver-impossible seam (same class as TTS
# init + fixture load in the e2e bootstrap); the observer supplies the path
# at BUILD time per phase, the ACTOR clicks the real button.
#
# Inherits the shared entry points — NO hand-rolled profile or package list:
#   scripts/e2e-profile.sh   (hermetic XDG_* profile, #99)
#   scripts/e2e-toolchain.sh (flake devShell toolchain, #101)
#
# Run from anywhere:   bash e2e/run-open-journey.sh
set -euo pipefail
cd "$(dirname "$0")/.."

source ./scripts/e2e-profile.sh
source ./scripts/e2e-toolchain.sh
APP_DIR="$E2E_PROFILE_DIR/com.lectrice.reader"
mkdir -p "$APP_DIR"
node scripts/gen-e2e-fixtures.mjs "$APP_DIR" >/dev/null
# The observer's corrupt fixture: garbage bytes with a .pdf name. It must
# EXIST so the open flow reaches pdf.js, which then throws.
printf '%%PDF-1.7 this is not a real pdf %s\n' "$(date +%s)" > "$APP_DIR/corrupt.pdf"

echo "==> Building frontend (VITE_E2E_NATIVE=true, seed=single) + both phases in the devShell"
export CI=true
toolchain_exec '
  set -euo pipefail
  export WEBKIT_WEBDRIVER="$(command -v WebKitWebDriver)"
  export WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 LIBGL_ALWAYS_SOFTWARE=1
  export GDK_BACKEND=x11
  DISPNUM_FILE=$(mktemp)
  Xvfb -displayfd 3 -screen 0 1280x1024x24 3>$DISPNUM_FILE >/tmp/lectrice-e2e-open-xvfb.log 2>&1 &
  XVFB_PID=$!
  trap "kill $XVFB_PID 2>/dev/null || true" EXIT
  for _ in $(seq 1 100); do [ -s $DISPNUM_FILE ] && break; sleep 0.1; done
  export DISPLAY=:$(cat $DISPNUM_FILE)
  echo "Xvfb ready on DISPLAY=$DISPLAY profile=$XDG_DATA_HOME"

  GOOD="$XDG_DATA_HOME/com.lectrice.reader/e2e-resume-fixture-b.pdf"
  CORRUPT="$XDG_DATA_HOME/com.lectrice.reader/corrupt.pdf"

  echo "==> PHASE open-good (VITE_E2E_OPEN_PATH=$GOOD)"
  GOOD_STATUS=0
  
( CI=true VITE_E2E_NATIVE=true VITE_E2E_NATIVE_TTS=none VITE_E2E_NATIVE_SEED=single \
    VITE_E2E_PROFILE_DIR="$XDG_DATA_HOME/com.lectrice.reader" \
    VITE_E2E_OPEN_PATH="$GOOD" pnpm build >/dev/null ) || GOOD_STATUS=$?
  if [ "$GOOD_STATUS" -eq 0 ]; then
    touch src-tauri/src/lib.rs
    ( cd src-tauri && cargo build --features e2e-tts-fixture >/dev/null 2>&1 )
    OPEN_PHASE=open-good E2E_SPEC=./e2e/open-journey.e2e.mjs pnpm test:e2e || GOOD_STATUS=$?
  fi
  echo "==> PHASE open-good exit: $GOOD_STATUS"

  echo "==> PHASE open-corrupt (VITE_E2E_OPEN_PATH=$CORRUPT)"
  CORRUPT_STATUS=0
  
( CI=true VITE_E2E_NATIVE=true VITE_E2E_NATIVE_TTS=none VITE_E2E_NATIVE_SEED=single \
    VITE_E2E_PROFILE_DIR="$XDG_DATA_HOME/com.lectrice.reader" \
    VITE_E2E_OPEN_PATH="$CORRUPT" pnpm build >/dev/null ) || CORRUPT_STATUS=$?
  if [ "$CORRUPT_STATUS" -eq 0 ]; then
    touch src-tauri/src/lib.rs
    ( cd src-tauri && cargo build --features e2e-tts-fixture >/dev/null 2>&1 )
    OPEN_PHASE=open-corrupt E2E_SPEC=./e2e/open-journey.e2e.mjs pnpm test:e2e || CORRUPT_STATUS=$?
  fi
  echo "==> PHASE open-corrupt exit: $CORRUPT_STATUS"

  echo "==> lane summary: open-good=$GOOD_STATUS open-corrupt=$CORRUPT_STATUS"
  [ "$GOOD_STATUS" -eq 0 ] && [ "$CORRUPT_STATUS" -eq 0 ]
'
