/**
 * Tauri Command Contracts
 *
 * This file documents the API contracts between frontend and backend.
 * The actual implementation is generated by tauri-specta in src/lib/bindings.ts
 *
 * @see src/lib/bindings.ts - Auto-generated TypeScript bindings
 * @see src-tauri/src/commands/ - Rust command implementations
 */

// =============================================================================
// RESULT TYPE
// =============================================================================

/**
 * All Tauri commands return a Result type that wraps success or error.
 * This matches the Rust Result<T, String> pattern.
 */
export type Result<T, E = string> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E };

// =============================================================================
// LIBRARY COMMANDS
// =============================================================================

/**
 * Document entity representing a PDF in the library.
 */
export interface Document {
  id: string;           // SHA-256 content hash
  filePath: string;     // Absolute filesystem path
  title: string | null;
  pageCount: number | null;
  currentPage: number;  // 1-indexed
  scrollPosition: number; // 0.0 - 1.0
  lastTtsChunkId: string | null;
  lastOpenedAt: string | null; // ISO 8601
  fileHash: string | null;
  createdAt: string;    // ISO 8601
}

export interface FileExistsResponse {
  exists: boolean;
  filePath: string;
}

/**
 * Library command contracts.
 * All commands prefixed with `library_` in Rust become `libraryXxx` in TypeScript.
 */
export interface LibraryCommands {
  /**
   * Add a new document to the library.
   * Uses SHA-256 content hash as ID for duplicate detection.
   */
  libraryAddDocument(
    filePath: string,
    title: string | null,
    pageCount: number | null
  ): Promise<Result<Document>>;

  /** Get a document by its content-hash ID */
  libraryGetDocument(id: string): Promise<Result<Document | null>>;

  /** Get a document by its file path */
  libraryGetDocumentByPath(filePath: string): Promise<Result<Document | null>>;

  /** Update reading progress for a document */
  libraryUpdateProgress(
    id: string,
    currentPage: number,
    scrollPosition: number | null,
    lastTtsChunkId: string | null
  ): Promise<Result<Document>>;

  /** Update document metadata (title, pageCount, fileHash) */
  libraryUpdateDocument(
    id: string,
    title: string | null,
    pageCount: number | null,
    fileHash: string | null
  ): Promise<Result<null>>;

  /**
   * List all documents in the library.
   * @param orderBy - Sort order: 'last_opened' | 'created' | 'title'
   */
  libraryListDocuments(
    orderBy: string | null,
    limit: number | null,
    offset: number | null
  ): Promise<Result<Document[]>>;

  /** Remove a document from the library */
  libraryRemoveDocument(id: string): Promise<Result<null>>;

  /** Mark a document as opened (updates lastOpenedAt) */
  libraryOpenDocument(id: string): Promise<Result<Document>>;

  /** Check if a document's file still exists on disk */
  libraryCheckFileExists(id: string): Promise<Result<FileExistsResponse>>;

  /** Update title of a document */
  libraryUpdateTitle(id: string, title: string): Promise<Result<Document>>;

  /** Relocate a document to a new path */
  libraryRelocateDocument(
    id: string,
    newFilePath: string
  ): Promise<Result<Document>>;
}

// =============================================================================
// HIGHLIGHT COMMANDS
// =============================================================================

export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Highlight {
  id: string;           // UUID v4
  documentId: string;
  pageNumber: number;   // 1-indexed
  rects: Rect[];
  color: string;        // Hex color #RRGGBB
  textContent: string | null;
  note: string | null;
  createdAt: string;    // ISO 8601
  updatedAt: string | null;
}

export interface CreateHighlightInput {
  documentId: string;
  pageNumber: number;
  rects: Rect[];
  color: string;
  textContent: string | null;
}

export interface BatchCreateResponse {
  highlights: Highlight[];
  created: number;
}

export interface DeleteResponse {
  success: boolean;
  deleted: number | null;
}

export interface ListHighlightsResponse {
  highlights: Highlight[];
}

export interface ExportResponse {
  content: string;
  filename: string;
}

/**
 * Highlight command contracts.
 */
export interface HighlightCommands {
  /** Create a new highlight */
  highlightsCreate(
    documentId: string,
    pageNumber: number,
    rects: Rect[],
    color: string,
    textContent: string | null
  ): Promise<Result<Highlight>>;

  /** Create multiple highlights in a batch */
  highlightsBatchCreate(
    highlights: CreateHighlightInput[]
  ): Promise<Result<BatchCreateResponse>>;

  /** List highlights for a specific page */
  highlightsListForPage(
    documentId: string,
    pageNumber: number
  ): Promise<Result<ListHighlightsResponse>>;

  /** List all highlights for a document */
  highlightsListForDocument(
    documentId: string
  ): Promise<Result<ListHighlightsResponse>>;

  /** Get a single highlight by ID */
  highlightsGet(id: string): Promise<Result<Highlight>>;

  /** Update a highlight's color or note */
  highlightsUpdate(
    id: string,
    color: string | null,
    note: string | null
  ): Promise<Result<Highlight>>;

  /** Delete a highlight */
  highlightsDelete(id: string): Promise<Result<DeleteResponse>>;

  /** Delete all highlights for a document */
  highlightsDeleteForDocument(
    documentId: string
  ): Promise<Result<DeleteResponse>>;

  /**
   * Export highlights to markdown or JSON.
   * @param format - 'markdown' | 'json' | 'text'
   */
  highlightsExport(
    documentId: string,
    format: string
  ): Promise<Result<ExportResponse>>;
}

// =============================================================================
// SETTINGS COMMANDS (Hexagonal API v2)
// =============================================================================

export interface SettingResponse {
  key: string;
  value: string | null; // JSON-encoded value
  updated: boolean;
}

export interface AllSettingsResponse {
  settings: Record<string, string>;
}

/**
 * Settings command contracts (v2 API using hexagonal architecture).
 */
export interface SettingsCommandsV2 {
  /** Get a setting value by key (returns JSON-encoded string) */
  settingsGetV2(key: string): Promise<Result<SettingResponse>>;

  /** Set a setting value (value is JSON-encoded) */
  settingsSetV2(key: string, value: string): Promise<Result<SettingResponse>>;

  /** Get all settings */
  settingsGetAllV2(): Promise<Result<AllSettingsResponse>>;

  /** Delete a setting */
  settingsDeleteV2(key: string): Promise<Result<SettingResponse>>;

  /** Set multiple settings at once */
  settingsSetBatchV2(
    settings: Array<{ key: string; value: string }>
  ): Promise<Result<{ updated: number }>>;
}

// =============================================================================
// TTS COMMANDS
// =============================================================================

export interface VoiceInfo {
  id: string;
  name: string;
  language: string | null;
}

export interface TtsState {
  initialized: boolean;
  isSpeaking: boolean;
  isPaused: boolean;
  currentChunkId: string | null;
  currentVoice: VoiceInfo | null;
  rate: number;
}

export interface TtsInitResponse {
  available: boolean;
  backend: string | null;
  defaultVoice: string | null;
  error: string | null;
}

export interface TtsCapabilities {
  supportsUtterance: boolean;
  supportsRate: boolean;
  supportsPitch: boolean;
  supportsVolume: boolean;
}

export interface TtsChunk {
  id: string;
  text: string;
}

/**
 * TTS command contracts.
 */
export interface TtsCommands {
  /** Initialize the TTS engine */
  ttsInit(): Promise<Result<TtsInitResponse>>;

  /** List available voices */
  ttsListVoices(): Promise<Result<VoiceInfo[]>>;

  /** Speak a single text chunk */
  ttsSpeak(text: string, chunkId: string | null): Promise<Result<null>>;

  /** Speak multiple chunks sequentially */
  ttsSpeakLong(chunks: TtsChunk[]): Promise<Result<null>>;

  /** Stop all speech */
  ttsStop(): Promise<Result<null>>;

  /** Pause current speech */
  ttsPause(): Promise<Result<null>>;

  /** Resume paused speech */
  ttsResume(): Promise<Result<null>>;

  /** Set the active voice */
  ttsSetVoice(voiceId: string): Promise<Result<null>>;

  /** Set playback rate (0.5 - 3.0) */
  ttsSetRate(rate: number): Promise<Result<null>>;

  /** Get current TTS state */
  ttsGetState(): Promise<Result<TtsState>>;

  /** Check engine capabilities */
  ttsCheckCapabilities(): Promise<Result<TtsCapabilities>>;
}

// =============================================================================
// COMBINED COMMAND INTERFACE
// =============================================================================

/**
 * Complete Tauri command interface.
 * This documents all available commands across all domains.
 */
export interface TauriCommands
  extends LibraryCommands,
    HighlightCommands,
    SettingsCommandsV2,
    TtsCommands {}
