#!/usr/bin/env python3
"""Build small cuts from the shipped favicon and original icon render exports.

Usage: build-small-cuts.py ORIGINAL_ICON_RENDER_DIR
No new artwork: bird = existing optical mark; feather/flight = simplified traces.
"""
from pathlib import Path
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'docs/brand/source-icons'
NS = 'http://www.w3.org/2000/svg'


def body(text):
    ET.fromstring(text)
    return text[text.index('>', text.index('<svg')) + 1:text.rindex('</svg>')].strip()


def run(*args):
    subprocess.run([str(arg) for arg in args], check=True)


bird = body((ROOT / 'docs/brand/lectrice-mark-small.svg').read_text())
# Remove comments only; preserve the complete nested transform tree.
bird = bird[bird.index('<g '):]


def perched(transform):
    return f'<g transform="{transform}">{bird}</g>'


cuts = {
    'play': perched('translate(2 1) scale(0.022)'),
    'library': perched('translate(4 0) scale(0.016)') +
               '<path fill="currentColor" d="M4 16h16v2.5H4z M4 20h16v2.5H4z"/>',
    'night': '<path fill="currentColor" d="M14 2a10 10 0 1 0 8 16 11 11 0 0 1-8-16z"/>' +
             perched('translate(12 3) scale(0.011)'),
    'narrate': perched('translate(1 2) scale(0.021)') +
               '<path d="M20 6a6 6 0 0 1 0 9" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
}
with tempfile.TemporaryDirectory() as directory:
    tmp = Path(directory)
    for name in ('bookmark', 'next'):
        png, mask, raw = tmp / 'source.png', tmp / 'mask.pbm', tmp / 'trace.svg'
        run('rsvg-convert', '-w', '192', '-h', '192', SOURCE / f'{name}-48.svg', '-o', png)
        # Close narrow paper slits: on black foreground this is Open (min then max).
        run('magick', png, '-background', 'white', '-alpha', 'remove', '-colorspace', 'Gray',
            '-threshold', '50%', '-morphology', 'Open', 'Disk:3', mask)
        run('potrace', '-s', '--turdsize', '8', '--opttolerance', '0.7', mask, '-o', raw)
        geometry = body(raw.read_text()).replace('fill="#000000"', 'fill="currentColor"')
        cuts[name] = f'<g transform="scale(0.125)">{geometry}</g>'

out = ROOT / 'docs/brand/small-cuts'
out.mkdir(parents=True, exist_ok=True)
for name, geometry in cuts.items():
    (out / f'{name}.svg').write_text(f'<svg xmlns="{NS}" viewBox="0 0 24 24">{geometry}</svg>\n')

# These JSX nodes are trusted, build-time geometry, not runtime HTML injection.
jsx = '/** Generated by tools/brand/build-small-cuts.py. Keep potrace transforms. */\nexport const smallCuts = {\n'
for name, geometry in cuts.items():
    geometry = geometry.replace('stroke-width=', 'strokeWidth=').replace('stroke-linecap=', 'strokeLinecap=')
    # SVG path whitespace/newlines are valid JSX attribute whitespace.
    jsx += f'  {name}: (<>\n{geometry}\n</>),\n'
jsx += '} as const;\n'
(ROOT / 'src/ui/icons/lectrice-small-cuts.tsx').write_text(jsx)
